name = input("enter customer name:")
mobile_no = int(input("enter customer number:"))
car_make = input("enter car make:")
car_model = input("enter car model:")
model_year = input("enter model year:")
price = input("enter price:")
fuel_type = input("enter fuel type:")
transmission_type = input("enter transmission type:")
prefered_color = input("enter prefered color:")

print(f"customer name is {name}")
print(f"customer mobile no: {mobile_no}")
print(f"car make: {car_make}")
print(f"model year: {model_year}")
print(f"price: {price}")
print(f"fuel type: {fuel_type}")
print(f"transmission type: {transmission_type}")
print(f"prefer color: {prefered_color}")